# Generated by Django 2.1 on 2018-08-30 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identity_Certificate', models.CharField(max_length=200)),
                ('Expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intermidiate_Certificate', models.TextField(default='999', max_length=200)),
                ('Expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Root_Certificate', models.TextField(default='999', max_length=200)),
                ('Expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('AirlineID_VendorID', models.CharField(default='XX', max_length=3)),
                ('Application_URL', models.URLField(default='test.com', primary_key=True, serialize=False)),
                ('Identity_Certificate', models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, to='Certificate_Tracker.Identity')),
            ],
        ),
        migrations.AddField(
            model_name='intermediate',
            name='Root_Certificate',
            field=models.ForeignKey(default='999', on_delete=django.db.models.deletion.CASCADE, to='Certificate_Tracker.Root'),
        ),
        migrations.AddField(
            model_name='identity',
            name='Intermidiate_Certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certificate_Tracker.Intermediate'),
        ),
        migrations.AddField(
            model_name='identity',
            name='Root_Certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Certificate_Tracker.Root'),
        ),
    ]
