# Generated by Django 2.1 on 2018-08-30 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediate',
            name='Intermidiate_Certificate',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='intermediate',
            name='Root_Certificate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Certificate_Tracker.Root'),
        ),
        migrations.AlterField(
            model_name='root',
            name='Root_Certificate',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='url',
            name='AirlineID_VendorID',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='url',
            name='Identity_Certificate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Certificate_Tracker.Identity'),
        ),
    ]
