# Generated by Django 2.1 on 2018-08-30 20:45

import Certificate_Tracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Certificate_Tracker', '0002_auto_20180830_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='Identity_Certificate',
            field=models.CharField(default='', max_length=200, verbose_name=Certificate_Tracker.models.Intermediate),
        ),
        migrations.AlterField(
            model_name='identity',
            name='Intermidiate_Certificate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Certificate_Tracker.Intermediate'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='Root_Certificate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Certificate_Tracker.Root'),
        ),
    ]
